version: '3.7'

services:
  backend:
    build: '.'
    container_name: backend
    ports:
      - '8080:8080'
    depends_on:
      - database
    env_file:
      - .env
  database:
    container_name: laundry-queue-db
    image: postgres:alpine
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_DB=laundry-queue
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
