server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database:5432/laundry-queue
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:migration
    enabled: true