server:
  port: 8080

spring:
  datasource:
    url: ${DATASOURCE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:migration
    enabled: true
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    protocol: ${MAIL_PROTOCOL}
mail:
  debug: ${MAIL_DEBUG}
security:
  access-secret-key: ${ACCESS_TOKEN_KEY}
  refresh-secret-key: ${REFRESH_TOKEN_KEY}
  access-lifetime-min: 30
  refresh-lifetime-days: 30
  permit-all:
    endpoints:
      - pattern: /api/login
        method: POST
      - pattern: /api/unsecured
        method: GET

application:
  queue-size: 5