server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database:5432/laundry-queue
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:migration
    enabled: true
  mail:
    host: host
    username: username
    password: password
    port: 0
    protocol: protocol
mail:
  debug: true
security:
  access-secret-key: access-secret-key-access-secret-key-access-secret-key
  refresh-secret-key: refresh-secret-key-refresh-secret-key-refresh-secret-key-
  access-lifetime-min: 30
  refresh-lifetime-days: 30
  permit-all:
    endpoints:
      - pattern: /api/login
        method: POST
      - pattern: /api/unsecured
        method: GET

application:
  queue-size: 5